spring.application.name=financeTracker
spring.datasource.url=jdbc:postgresql://localhost:5432/fincanceDB
spring.datasource.username=postgres
spring.datasource.password=anis1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true